# Generated by Django 3.2.2 on 2021-05-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(help_text='Primary Key for table', primary_key=True, serialize=False, unique=True)),
                ('emp_fname', models.CharField(help_text='First Name', max_length=100)),
                ('emp_lastname', models.CharField(help_text='Last Name', max_length=100)),
                ('emp_qualification', models.CharField(help_text='Qualification', max_length=200)),
                ('emp_expectedsalary', models.CharField(help_text='Expected Salary', max_length=100)),
                ('emp_contact_no', models.CharField(help_text='Contact number', max_length=10, unique=True)),
                ('emp_email', models.CharField(help_text='Email Address', max_length=100)),
            ],
        ),
    ]
